// code generated by pbf v4.0.1

export function readglyph(pbf, end) {
    return pbf.readFields(readglyphField, {id: 0, bitmap: undefined, width: 0, height: 0, left: 0, top: 0, advance: 0}, end);
}
function readglyphField(tag, obj, pbf) {
    if (tag === 1) obj.id = pbf.readVarint();
    else if (tag === 2) obj.bitmap = pbf.readBytes();
    else if (tag === 3) obj.width = pbf.readVarint();
    else if (tag === 4) obj.height = pbf.readVarint();
    else if (tag === 5) obj.left = pbf.readSVarint();
    else if (tag === 6) obj.top = pbf.readSVarint();
    else if (tag === 7) obj.advance = pbf.readVarint();
}

/**
 * !important
 * Manually overwritten to handle 0 values if(0)
 * When if prop value is 0 it will not be written properly
 * Some values could lead to NaN values when omitted and used in calculations
 */
export function writeglyph(obj, pbf) {
    if (obj.id !== undefined) pbf.writeVarintField(1, obj.id);
    if (obj.bitmap != null) pbf.writeBytesField(2, obj.bitmap);
    if (obj.width !== undefined) pbf.writeVarintField(3, obj.width);
    if (obj.height !== undefined) pbf.writeVarintField(4, obj.height);
    if (obj.left !== undefined) pbf.writeSVarintField(5, obj.left);
    if (obj.top !== undefined) pbf.writeSVarintField(6, obj.top);
    if (obj.advance !== undefined) pbf.writeVarintField(7, obj.advance);
}

export function readfontstack(pbf, end) {
    return pbf.readFields(readfontstackField, {name: "", range: "", glyphs: []}, end);
}
function readfontstackField(tag, obj, pbf) {
    if (tag === 1) obj.name = pbf.readString();
    else if (tag === 2) obj.range = pbf.readString();
    else if (tag === 3) obj.glyphs.push(readglyph(pbf, pbf.readVarint() + pbf.pos));
}
export function writefontstack(obj, pbf) {
    if (obj.name) pbf.writeStringField(1, obj.name);
    if (obj.range) pbf.writeStringField(2, obj.range);
    if (obj.glyphs) for (const item of obj.glyphs) pbf.writeMessage(3, writeglyph, item);
}

export function readglyphs(pbf, end) {
    return pbf.readFields(readglyphsField, {stacks: []}, end);
}
function readglyphsField(tag, obj, pbf) {
    if (tag === 1) obj.stacks.push(readfontstack(pbf, pbf.readVarint() + pbf.pos));
}
export function writeglyphs(obj, pbf) {
    if (obj.stacks) for (const item of obj.stacks) pbf.writeMessage(1, writefontstack, item);
}
